/* test_bytematch.c — FAIL-first pins for the C port.
 * Pin 2 is the crown: the kernel journal bytes must match, entry for entry,
 * the reference bytes generated by gen_expected_journal.py from the same
 * spec read out of src/engine.c. If the reference file is absent the pin
 * reports SKIP (honest) instead of passing vacuously.
 */
#include "core.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int passed = 0, failed = 0, skipped = 0;

static void report(const char *name, int ok, const char *detail) {
    if (ok) { passed++; printf("  PASS %s%s%s\n", name, detail ? " — " : "", detail ? detail : ""); }
    else    { failed++; printf("  FAIL %s%s%s\n", name, detail ? " — " : "", detail ? detail : ""); }
}
#define SKIP(name, why) do { skipped++; printf("  SKIP %s — %s\n", name, why); } while (0)

static char *hex_of(const uint8_t *b, size_t n, char *out, size_t cap) {
    size_t o = 0;
    for (size_t i = 0; i < n && o + 2 < cap; i++) o += (size_t)snprintf(out + o, cap - o, "%02x", b[i]);
    return out;
}

static int read_file(const char *path, char *out, size_t cap) {
    FILE *f = fopen(path, "r");
    if (!f) return -1;
    if (!fgets(out, (int)cap, f)) { fclose(f); return -1; }
    out[strcspn(out, "\r\n")] = 0;
    fclose(f);
    return 0;
}

static void op(qfabric_t *f, const char *name, const char *cell, const char *other,
               long long v, const char *kind, char **reads, int nr, char *rcpt, size_t cap) {
    qf_op(f, name, cell, other, v, kind, reads, nr, rcpt, cap);
}

int main(void) {
    char r[512], g[17], hex[4096];

    /* 1. the hash itself, classic FNV-1a vector */
    {
        uint64_t h = qf_fnv1a64((const uint8_t *)"a", 1);
        report("fnv1a64('a') == af63dc4c8601ec8c", h == 0xaf63dc4c8601ec8cULL, NULL);
    }

    /* 2. journal byte-exact vs the python reference */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 1, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "B1", NULL, 3, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "A1", NULL, 2, "generic", NULL, 0, r, sizeof r);
        op(&f, "LINK", "A1", "B1", 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "EFFECT", "A1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "TICK", "", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "VIEW", "A1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "FORGET", "B1", NULL, 0, "generic", NULL, 0, r, sizeof r);

        char expected[8192], expected_g[64];
        if (read_file("expected_journal.hex", expected, sizeof expected) != 0) {
            SKIP("journal bytes == python reference", "expected_journal.hex missing (run: python3 gen_expected_journal.py > expected_journal.hex)");
        } else {
            hex_of(f.journal, f.e.journal_len, hex, sizeof hex);
            report("journal bytes == python reference", strcmp(hex, expected) == 0, hex);
            if (read_file("expected_gdigest.txt", expected_g, sizeof expected_g) == 0) {
                qf_gdigest(&f, g);
                report("gdigest == python fnv1a64(journal)", strcmp(g, expected_g) == 0, g);
            }
        }
    }

    /* 3. BIND idempotent — identical rebind grows neither version nor journal */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 7, "generic", NULL, 0, r, sizeof r);
        size_t jl = f.e.journal_len;
        op(&f, "BIND", "A1", NULL, 7, "generic", NULL, 0, r, sizeof r);
        report("BIND idempotent (no journal growth)", f.e.journal_len == jl, r);
    }

    /* 4. VIEW pure — fabric digest unmoved */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 5, "generic", NULL, 0, r, sizeof r);
        qf_gdigest(&f, g);
        char before[17]; snprintf(before, 17, "%s", g);
        op(&f, "VIEW", "A1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        qf_gdigest(&f, g);
        report("VIEW pure (gdigest stable)", strcmp(g, before) == 0, g);
    }

    /* 5. TICK monotonic + journal records it */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 1, "generic", NULL, 0, r, sizeof r);
        op(&f, "TICK", "", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "TICK", "", NULL, 0, "generic", NULL, 0, r, sizeof r);
        report("TICK monotonic", f.e.tick == 2, r);
    }

    /* 6. formula cell: sum over reads via the kernel evaluator slot */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 1, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "B1", NULL, 2, "generic", NULL, 0, r, sizeof r);
        char *reads[2] = { "A1", "B1" };
        op(&f, "BIND", "C1", NULL, 0, "sum", reads, 2, r, sizeof r);
        op(&f, "EFFECT", "C1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "VIEW", "C1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        report("formula sum(A1,B1) == 3", strstr(r, "\"value\":3") != NULL, r);
    }

    /* 7. DAG law: back-edge rejected, exactly one LINK journaled */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 1, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "B1", NULL, 2, "generic", NULL, 0, r, sizeof r);
        op(&f, "LINK", "A1", "B1", 0, "generic", NULL, 0, r, sizeof r);
        int links = 0;
        for (size_t i = 0; i < f.e.journal_len; ) {
            uint8_t opc = f.journal[i];
            uint16_t ilen = (uint16_t)f.journal[i + 1] | ((uint16_t)f.journal[i + 2] << 8);
            i += 3 + ilen + 8;
            if (opc == 1) links++;
        }
        op(&f, "LINK", "B1", "A1", 0, "generic", NULL, 0, r, sizeof r);
        int ok = (strstr(r, "\"ok\":false") != NULL);
        op(&f, "VIEW", "A1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        report("DAG law: B1->A1 rejected", ok && links == 1, r);
    }

    /* 8. FORGET complete — cell gone, VIEW fails, survivor intact */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 1, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "B1", NULL, 2, "generic", NULL, 0, r, sizeof r);
        op(&f, "FORGET", "B1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "VIEW", "B1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        int gone = (strstr(r, "\"ok\":false") != NULL);
        op(&f, "VIEW", "A1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        int alive = (strstr(r, "\"ok\":true") != NULL);
        report("FORGET complete", gone && alive, r);
    }

    /* 9. TICK re-evaluates formula cells (dirty set) */
    {
        qfabric_t f; qf_init(&f);
        op(&f, "BIND", "A1", NULL, 1, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "B1", NULL, 2, "generic", NULL, 0, r, sizeof r);
        char *reads[2] = { "A1", "B1" };
        op(&f, "BIND", "C1", NULL, 0, "sum", reads, 2, r, sizeof r);
        op(&f, "EFFECT", "C1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "BIND", "A1", NULL, 5, "generic", NULL, 0, r, sizeof r);
        op(&f, "TICK", "", NULL, 0, "generic", NULL, 0, r, sizeof r);
        op(&f, "VIEW", "C1", NULL, 0, "generic", NULL, 0, r, sizeof r);
        report("TICK re-evaluates formulas (5+2==7)", strstr(r, "\"value\":7") != NULL, r);
    }

    printf("\n%d passed, %d failed, %d skipped\n", passed, failed, skipped);
    return failed ? 1 : 0;
}
